server:
# Source: Accomplist Gambling Domains
# URL: https://github.com/cbuijs/accomplist
# Updated: 09/07/2026 19:48:05,35
# Total Domains: 2

local-zone: "429: Too Many Requests." always_nxdomain
local-zone: "For more on scraping GitHub and how it may affect your rights, please review our Terms of Service (https://docs.github.com/en/site-policy/github-terms/github-terms-of-service).." always_nxdomain
