server:
# Source: CERT Polska Warning List
# URL: https://hole.cert.pl/domains/v2/domains.txt
# Updated: 27/05/2026 20:37:53,22

local-zone: "<html><body><h1>408 Request Time-out</h1>." always_nxdomain
local-zone: "Your browser didn't send a complete request in time.." always_nxdomain
local-zone: "</body></html>." always_nxdomain
