server:
# Source: Frogeye FirstParty-Only Trackers
# URL: https://hostfiles.frogeye.fr/firstparty-only-trackers.txt
# Updated: 19/05/2026 12:21:15,25

local-zone: "<DOCTYPE html>." always_nxdomain
local-zone: "<html>." always_nxdomain
local-zone: "<head>." always_nxdomain
local-zone: "    <title>Oh no Bad Gateway</title>." always_nxdomain
local-zone: "    <link rel="stylesheet" href="https://assets.frogeye.fr/default.css?cacheBust=XVCh0qnI3MFOh0pG3CYXlg"/>." always_nxdomain
local-zone: "    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>." always_nxdomain
local-zone: "    <meta name="referrer" content="origin"/>." always_nxdomain
local-zone: "    ." always_nxdomain
local-zone: "    ." always_nxdomain
local-zone: "    ." always_nxdomain
local-zone: "</head>." always_nxdomain
local-zone: "<body id="top">." always_nxdomain
local-zone: "<main>." always_nxdomain
local-zone: "    <center>." always_nxdomain
local-zone: "        <h1 id="title" class=".centered-div">Oh no Bad Gateway</h1>." always_nxdomain
local-zone: "    </center>." always_nxdomain
local-zone: "    <div class="centered-div">." always_nxdomain
local-zone: "        <img." always_nxdomain
local-zone: "                id="image"." always_nxdomain
local-zone: "                style="width:100%;max-width:256px;"." always_nxdomain
local-zone: "                src="https://assets.frogeye.fr/flower.svg"." always_nxdomain
local-zone: "        />." always_nxdomain
local-zone: "        ." always_nxdomain
local-zone: "        <p id="status">Error: dial tcp [2a10:3781:2abd:7:3e7c:3fff:fe21:2fdc]:7283: connect: connection timed out</p>." always_nxdomain
local-zone: "        ." always_nxdomain
local-zone: "        <details>." always_nxdomain
local-zone: "            <summary>Why am I seeing this?</summary>." always_nxdomain
local-zone: "            ." always_nxdomain
local-zone: "<p>." always_nxdomain
local-zone: "	You are seeing this because the administrator of this website has set up <a href="https://git.gammaspectra.live/git/go-away">go-away</a> ." always_nxdomain
local-zone: "	to protect the server against the scourge of <a href="https://thelibre.news/foss-infrastructure-is-under-attack-by-ai-companies/">AI companies aggressively scraping websites</a>.." always_nxdomain
local-zone: "</p>." always_nxdomain
local-zone: "<p>." always_nxdomain
local-zone: "	Mass scraping can and does cause downtime for the websites, which makes their resources inaccessible for everyone.." always_nxdomain
local-zone: "</p>." always_nxdomain
local-zone: "<p>." always_nxdomain
local-zone: "	Please note that some challenges requires the use of modern JavaScript features and some plugins may disable these.." always_nxdomain
local-zone: "	Disable such plugins for this domain (for example, JShelter) if you encounter any issues.." always_nxdomain
local-zone: "</p>." always_nxdomain
local-zone: "        </details>." always_nxdomain
local-zone: "        ." always_nxdomain
local-zone: "        ." always_nxdomain
local-zone: "        <p><small>If you have any issues contact the site administrator and provide the following Request Id: <em>1b46346b47573ba6fb8d210808be17be</em></small></p>." always_nxdomain
local-zone: "    </div>." always_nxdomain
local-zone: "    <footer>." always_nxdomain
local-zone: "        <center>." always_nxdomain
local-zone: "            <p>." always_nxdomain
local-zone: "                Protected by <a href="https://git.gammaspectra.live/git/go-away">go-away</a> :: Request Id <em>1b46346b47573ba6fb8d210808be17be</em>." always_nxdomain
local-zone: "                ." always_nxdomain
local-zone: "            </p>." always_nxdomain
local-zone: "        </center>." always_nxdomain
local-zone: "    </footer>." always_nxdomain
local-zone: "    ." always_nxdomain
local-zone: "</main>." always_nxdomain
local-zone: "</body>." always_nxdomain
local-zone: "</html>." always_nxdomain
