server:
# Source : cbuijs NRD 1 Day
# URL    : https://github.com/cbuijs/nrd
# Mode   : always_nxdomain
# Domains: 66
# Updated: 08/05/2026  0:58:37,54

local-zone: "1516-ai.net." always_nxdomain 
local-zone: "1-electric.net." always_nxdomain 
local-zone: "4-promo.net." always_nxdomain 
local-zone: "a-collective.world." always_nxdomain 
local-zone: "ai-ice.net." always_nxdomain 
local-zone: "ai-it.net." always_nxdomain 
local-zone: "a-o-s.net." always_nxdomain 
local-zone: "atticus-innovations-claw.cloud." always_nxdomain 
local-zone: "avalion-server.net." always_nxdomain 
local-zone: "beyondblobnative-ai.studio." always_nxdomain 
local-zone: "board-gaming.net." always_nxdomain 
local-zone: "buy-doma.xyz." always_nxdomain 
local-zone: "ceipo-usa.net." always_nxdomain 
local-zone: "china-google.net." always_nxdomain 
local-zone: "dream-iptv.online." always_nxdomain 
local-zone: "eclip-se.net." always_nxdomain 
local-zone: "enter-one.store." always_nxdomain 
local-zone: "fan-com.net." always_nxdomain 
local-zone: "future-play.net." always_nxdomain 
local-zone: "ge-free.net." always_nxdomain 
local-zone: "grounded-app.net." always_nxdomain 
local-zone: "hochneukircher-tc.net." always_nxdomain 
local-zone: "hthsport-app.net." always_nxdomain 
local-zone: "i-be.net." always_nxdomain 
local-zone: "ice-ai.net." always_nxdomain 
local-zone: "ivan-it.net." always_nxdomain 
local-zone: "jackpot-jill-casino.click." always_nxdomain 
local-zone: "juicy-ai.net." always_nxdomain 
local-zone: "juicy-calendar.online." always_nxdomain 
local-zone: "just-josh-it.net." always_nxdomain 
local-zone: "kaiyuan-game.net." always_nxdomain 
local-zone: "kaiyuanqipan-game.net." always_nxdomain 
local-zone: "kyty-app.net." always_nxdomain 
local-zone: "labs-intel-nexus.xyz." always_nxdomain 
local-zone: "levitexaplus-order.store." always_nxdomain 
local-zone: "local-io.net." always_nxdomain 
local-zone: "lucky-hills-casino.online." always_nxdomain 
local-zone: "lumio-ai.net." always_nxdomain 
local-zone: "ma-ai.net." always_nxdomain 
local-zone: "maestro-ai.net." always_nxdomain 
local-zone: "medbilling-360.net." always_nxdomain 
local-zone: "mert-online.net." always_nxdomain 
local-zone: "miura-cn.net." always_nxdomain 
local-zone: "miyako-h.net." always_nxdomain 
local-zone: "mr-ai.net." always_nxdomain 
local-zone: "n-i-a.net." always_nxdomain 
local-zone: "paito-hk.net." always_nxdomain 
local-zone: "repair-my-auto.live." always_nxdomain 
local-zone: "resort-bc.casino." always_nxdomain 
local-zone: "robocat-casino.online." always_nxdomain 
local-zone: "santa-ai.net." always_nxdomain 
local-zone: "saude-nova.xyz." always_nxdomain 
local-zone: "service-clientes.cloud." always_nxdomain 
local-zone: "sherpa-ai.net." always_nxdomain 
local-zone: "si-korea.net." always_nxdomain 
local-zone: "solo-ops.net." always_nxdomain 
local-zone: "suite-ops.net." always_nxdomain 
local-zone: "taoc-app.net." always_nxdomain 
local-zone: "tenmon-ark.info." always_nxdomain 
local-zone: "thabet-app.net." always_nxdomain 
local-zone: "ton-app.net." always_nxdomain 
local-zone: "tvzio-sumup.store." always_nxdomain 
local-zone: "viet-lotto.net." always_nxdomain 
local-zone: "volcano-facts.net." always_nxdomain 
local-zone: "vr-ai.net." always_nxdomain 
local-zone: "z-pentest-atlanta.net." always_nxdomain 
