server:
# Source : cbuijs NRD 1 Day
# URL    : https://github.com/cbuijs/nrd
# Mode   : always_nxdomain
# Domains: 72
# Updated: 19/06/2026  7:33:32,30

local-zone: "136-placeholder.com." always_nxdomain 
local-zone: "1436.eu.cc." always_nxdomain 
local-zone: "20betkasino-sk.com." always_nxdomain 
local-zone: "a8-bians-qq.com." always_nxdomain 
local-zone: "anchored-agency.com." always_nxdomain 
local-zone: "animabonn-studio.com." always_nxdomain 
local-zone: "appli-corp.com." always_nxdomain 
local-zone: "arbitrax-flow.com." always_nxdomain 
local-zone: "asen-co.com." always_nxdomain 
local-zone: "axial-motor.com." always_nxdomain 
local-zone: "b2y-store.com." always_nxdomain 
local-zone: "beautyundwellness-aalen.de." always_nxdomain 
local-zone: "blacklabelcasino-se.com." always_nxdomain 
local-zone: "bluebay-hotels.com." always_nxdomain 
local-zone: "cashbox-uk.com." always_nxdomain 
local-zone: "ccrxdrcp.cn.com." always_nxdomain 
local-zone: "chs-jizhibo-qq.com.cn." always_nxdomain 
local-zone: "churchscientology.pp.ua." always_nxdomain 
local-zone: "crazytime-opinie.pl." always_nxdomain 
local-zone: "dazzle-casino.org." always_nxdomain 
local-zone: "enchanted-hands.com." always_nxdomain 
local-zone: "ethereum-online-casino.com." always_nxdomain 
local-zone: "exempt-route.com." always_nxdomain 
local-zone: "fachpsychotherapie-hamburg.com." always_nxdomain 
local-zone: "familym-com.net." always_nxdomain 
local-zone: "fb-gy.eu.cc." always_nxdomain 
local-zone: "fekic-play.com." always_nxdomain 
local-zone: "ferme-normandie.fr." always_nxdomain 
local-zone: "hugo-test.com." always_nxdomain 
local-zone: "immediatev4-app.com." always_nxdomain 
local-zone: "insights-bet.com." always_nxdomain 
local-zone: "jhkln9jmm.eu.cc." always_nxdomain 
local-zone: "jokun-studio.com." always_nxdomain 
local-zone: "joo-de.de." always_nxdomain 
local-zone: "joyfidelis-cloud.com." always_nxdomain 
local-zone: "jt-one.com." always_nxdomain 
local-zone: "kairos-law-ai.com." always_nxdomain 
local-zone: "kofemash-rem.ru." always_nxdomain 
local-zone: "kz-olimp-casino.org." always_nxdomain 
local-zone: "leruisseau-france.fr." always_nxdomain 
local-zone: "link-building-uk.com." always_nxdomain 
local-zone: "llm-releases.com." always_nxdomain 
local-zone: "loopearplugs-za.com." always_nxdomain 
local-zone: "luckywave-gb.com." always_nxdomain 
local-zone: "magicial-atlas.site." always_nxdomain 
local-zone: "magiuscasino-portugal.com." always_nxdomain 
local-zone: "merge-pdf.online." always_nxdomain 
local-zone: "mon-couvreur-yvelines.fr." always_nxdomain 
local-zone: "moorestherapyll.com.de." always_nxdomain 
local-zone: "morrlandhealthc.com.de." always_nxdomain 
local-zone: "newsletter-api.org." always_nxdomain 
local-zone: "oral-vita.com." always_nxdomain 
local-zone: "oraxis-agency.com." always_nxdomain 
local-zone: "paymentcard-create.com." always_nxdomain 
local-zone: "pialadunia.eu.cc." always_nxdomain 
local-zone: "playdoit-app.com." always_nxdomain 
local-zone: "promelsa-pe.com." always_nxdomain 
local-zone: "protegelite-es.com." always_nxdomain 
local-zone: "rf-cs.com." always_nxdomain 
local-zone: "rna-gov.com." always_nxdomain 
local-zone: "seine-ouest-expertise.com." always_nxdomain 
local-zone: "studio-hermes.com." always_nxdomain 
local-zone: "support-startrader.com." always_nxdomain 
local-zone: "telegaepta.eu.cc." always_nxdomain 
local-zone: "thursdayboot-nz.com." always_nxdomain 
local-zone: "toiture-drome-gard-vaucluse.fr." always_nxdomain 
local-zone: "true-maps.org." always_nxdomain 
local-zone: "trymark-ai.com." always_nxdomain 
local-zone: "veridia-org.com." always_nxdomain 
local-zone: "weblive.eu.cc." always_nxdomain 
local-zone: "weplay-au.com." always_nxdomain 
local-zone: "wolfwinner-au-vip.com." always_nxdomain 
