server:
# Source : cbuijs NRD 1 Day
# URL    : https://github.com/cbuijs/nrd
# Mode   : always_nxdomain
# Domains: 2
# Updated: 08/07/2026 14:04:45,12

local-zone: "429: Too Many Requests." always_nxdomain 
local-zone: "For more on scraping GitHub and how it may affect your rights, please review our Terms of Service (https://docs.github.com/en/site-policy/github-terms/github-terms-of-service).." always_nxdomain 
