server:
# Source: PhishDestroy DestroyList
# URL: https://raw.githubusercontent.com/phishdestroy/destroylist/refs/heads/main/list.txt
# NOTE: Entries converted AS-IS (no filtering)
# Updated: 07/07/2026  1:49:45,94

local-zone: "429: Too Many Requests." always_nxdomain
local-zone: "For more on scraping GitHub and how it may affect your rights, please review our Terms of Service (https://docs.github.com/en/site-policy/github-terms/github-terms-of-service).." always_nxdomain
