server:
# Source: ShadowWhisperer Adult BlockList
# Updated: 07/07/2026  1:50:37,15

local-zone: "429: Too Many Requests." always_nxdomain
local-zone: "For more on scraping GitHub and how it may affect your rights, please review our Terms of Service (https://docs.github.com/en/site-policy/github-terms/github-terms-of-service).." always_nxdomain
