server:
# ========================================================
# NAMA LIST     : AssoEchap Stalkerware Indicators
# URL           : https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/refs/heads/master/generated/hosts_full
# JUMLAH DOMAIN : 1
# UPDATE PADA   : 27/06/2026 20:34:58,48
# ========================================================

local-zone: "400:." always_nxdomain 
