server:
# Source: xRuffKez TIF Domains
# URL: https://codeberg.org/xRuffKez/tif
# Updated: 09/06/2026 15:19:50,90
# Total Domains: 57

local-zone: "<DOCTYPE html>." always_nxdomain
local-zone: "<html lang=en-US data-theme=codeberg-auto>." always_nxdomain
local-zone: "<head>." always_nxdomain
local-zone: "<meta name=viewport content=width=device-width, initial-scale=1>." always_nxdomain
local-zone: "<title>Internal server error - Codeberg.org</title>." always_nxdomain
local-zone: "<link rel=icon href=/assets/img/favicon.svg type=image/svg+xml>." always_nxdomain
local-zone: "<link rel=alternate icon href=/assets/img/favicon.png type=image/png>." always_nxdomain
local-zone: "<link rel=stylesheet href=/assets/css/index.css?v=15.0.0-156-02d7aaa8~gitea-1.22.0>." always_nxdomain
local-zone: "<link rel=stylesheet href=/assets/css/theme-codeberg-auto.css?v=15.0.0-156-02d7aaa8~gitea-1.22.0>." always_nxdomain
local-zone: "</head>." always_nxdomain
local-zone: "<body>." always_nxdomain
local-zone: "<div class=full height>." always_nxdomain
local-zone: "<nav id=navbar aria-label=Navigation bar>." always_nxdomain
local-zone: "<div class=navbar-left ui secondary menu>." always_nxdomain
local-zone: "<a class=item id=navbar-logo href=/ aria-label=Home>." always_nxdomain
local-zone: "<div class=branding aria-hidden=true>." always_nxdomain
local-zone: "<img width=30 height=30 class=light-logo loading=lazy src=/assets/img/svg/cb-logo.svg alt=Logo>." always_nxdomain
local-zone: "<img width=30 height=30 class=dark-logo loading=lazy src=/assets/img/svg/cb-logo-mono.svg alt=Logo>." always_nxdomain
local-zone: "</div>." always_nxdomain
local-zone: "</a>." always_nxdomain
local-zone: "</div>." always_nxdomain
local-zone: "</nav>." always_nxdomain
local-zone: "<div role=main class=page-content status-page-500>." always_nxdomain
local-zone: "<div class=ui container >." always_nxdomain
local-zone: "<style> .ui.message.flash-message { text-align: left; } </style>." always_nxdomain
local-zone: ""=." always_nxdomain
local-zone: "<div id=flash-message hx-swap-oob=true></div>." always_nxdomain
local-zone: "</div>." always_nxdomain
local-zone: "<div class=ui container center>." always_nxdomain
local-zone: "<h1 class=tw-mt-8 error-code>500</h1>." always_nxdomain
local-zone: "<p>Internal server error</p>." always_nxdomain
local-zone: "</div>." always_nxdomain
local-zone: "<div class=divider></div>." always_nxdomain
local-zone: "<div class=ui container tw-my-8>." always_nxdomain
local-zone: ""=." always_nxdomain
local-zone: "<div class=center tw-mt-8>." always_nxdomain
local-zone: "<p>Forgejo version: 15.0.0-156-02d7aaa8&#43;gitea-1.22.0</p>." always_nxdomain
local-zone: ""=." always_nxdomain
local-zone: "</div>." always_nxdomain
local-zone: "</div>." always_nxdomain
local-zone: "</div>." always_nxdomain
local-zone: "</div>." always_nxdomain
local-zone: ""=." always_nxdomain
local-zone: "<script type=module>." always_nxdomain
local-zone: "const embedded = document.querySelector('.page-content .page-content.status-page-500');." always_nxdomain
local-zone: "if (embedded) {." always_nxdomain
local-zone: ""=." always_nxdomain
local-zone: "const embeddedParent = embedded.parentNode;." always_nxdomain
local-zone: "let main = document.querySelector('.page-content');." always_nxdomain
local-zone: "main = main ?? document.querySelector('body');." always_nxdomain
local-zone: "main.prepend(document.createElement('hr'));." always_nxdomain
local-zone: "main.prepend(embedded);." always_nxdomain
local-zone: "embeddedParent.remove(); ." always_nxdomain
local-zone: "}." always_nxdomain
local-zone: "</script>." always_nxdomain
local-zone: "</body>." always_nxdomain
local-zone: "</html>." always_nxdomain
