server:
# Source: xRuffKez TIF Domains
# URL: https://codeberg.org/xRuffKez/tif
# Updated: 27/05/2026  1:56:02,52
# Total Domains: 3

local-zone: "<html><body><h1>504 Gateway Time-out</h1>." always_nxdomain
local-zone: "The server didn't respond in time.." always_nxdomain
local-zone: "</body></html>." always_nxdomain
