server:
# Title: HaGeZi Xiaomi Native Allowlist
# Description: Allow Xiaomi-related domains
# Updated: 30/06/2026 20:55:10,78
local-zone: "<?xml version="1.0" encoding="utf-8"?>." always_transparent
local-zone: "<DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"." always_transparent
local-zone: " "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">." always_transparent
local-zone: "<html>." always_transparent
local-zone: "  <head>." always_transparent
local-zone: "    <title>503 No healthy backends</title>." always_transparent
local-zone: "  </head>." always_transparent
local-zone: "  <body>." always_transparent
local-zone: "    <h1>Error 503 No healthy backends</h1>." always_transparent
local-zone: "    <p>No healthy backends</p>." always_transparent
local-zone: "    <h3>Error 54113</h3>." always_transparent
local-zone: "    <p>Details: cache-sin-wsap440078-SIN 1782827711 2178695239</p>." always_transparent
local-zone: "    <hr>." always_transparent
local-zone: "    <p>Varnish cache server</p>." always_transparent
local-zone: "  </body>." always_transparent
local-zone: "</html>." always_transparent
