server:
# Source: ShadowWhisperer Whitelist
# Updated: 09/07/2026  5:06:36,45
local-zone: "429: Too Many Requests." always_transparent
local-zone: "For more on scraping GitHub and how it may affect your rights, please review our Terms of Service (https://docs.github.com/en/site-policy/github-terms/github-terms-of-service).." always_transparent
