server:
# Source: cbuijs NRD 1 Day
# URL: https://github.com/cbuijs/nrd
# Updated: 07/10/2026 11:57:23,72
# Total Domains: 39

local-zone: "148148.eu.cc." always_nxdomain
local-zone: "fewo-willingen-hessen.de." always_nxdomain
local-zone: "fit4-work.de." always_nxdomain
local-zone: "gospel.uk.com." always_nxdomain
local-zone: "gott-wissen.de." always_nxdomain
local-zone: "gruenderwerkstatt-koeln.de." always_nxdomain
local-zone: "hubs-pandasport-qq.com.cn." always_nxdomain
local-zone: "i-urlop.pl." always_nxdomain
local-zone: "jeans.uk.com." always_nxdomain
local-zone: "kalonji-indian-food-berlin.de." always_nxdomain
local-zone: "lan-z.cn." always_nxdomain
local-zone: "let.uk.com." always_nxdomain
local-zone: "looks.uk.com." always_nxdomain
local-zone: "magicien-orleans.fr." always_nxdomain
local-zone: "manage.uk.com." always_nxdomain
local-zone: "monk.uk.com." always_nxdomain
local-zone: "navigation.uk.com." always_nxdomain
local-zone: "novasoft.uk.com." always_nxdomain
local-zone: "nts-metro.ru." always_nxdomain
local-zone: "psychologe-online.de." always_nxdomain
local-zone: "reach.uk.com." always_nxdomain
local-zone: "renates-esoterik-welt.de." always_nxdomain
local-zone: "rtxpml.uk.com." always_nxdomain
local-zone: "salonkosmetyczny-lublin.pl." always_nxdomain
local-zone: "soar.uk.com." always_nxdomain
local-zone: "sps-weiterbildung.de." always_nxdomain
local-zone: "style-74.ru." always_nxdomain
local-zone: "sunday.uk.com." always_nxdomain
local-zone: "supersonic-welt.de." always_nxdomain
local-zone: "taxreturn.uk.com." always_nxdomain
local-zone: "tiempo.uk.com." always_nxdomain
local-zone: "tle.uk.com." always_nxdomain
local-zone: "tmc-trier.de." always_nxdomain
local-zone: "town.uk.com." always_nxdomain
local-zone: "twoje-kasyno.co.pl." always_nxdomain
local-zone: "uklid-trebic.cz." always_nxdomain
local-zone: "web-und-blog.de." always_nxdomain
local-zone: "win-it-mail.de." always_nxdomain
local-zone: "zomedical.uk.com." always_nxdomain
