server:
# Source: cbuijs NRD 1 Day
# URL: https://github.com/cbuijs/nrd
# Updated: 13/09/2026 20:50:59,99
# Total Domains: 15

local-zone: "betti-casino.click." always_nxdomain
local-zone: "brionis-casino.click." always_nxdomain
local-zone: "deepl-download-hub.xyz." always_nxdomain
local-zone: "dymension-hub.xyz." always_nxdomain
local-zone: "fontan-casino.click." always_nxdomain
local-zone: "genesis-block.xyz." always_nxdomain
local-zone: "globeapp-trade.xyz." always_nxdomain
local-zone: "goldbet--casino.click." always_nxdomain
local-zone: "helloworld-download-hub.xyz." always_nxdomain
local-zone: "launchpad-taiko.xyz." always_nxdomain
local-zone: "main-hub.xyz." always_nxdomain
local-zone: "plataformadeinversionenlinea-trade.xyz." always_nxdomain
local-zone: "stonevegas-casino.click." always_nxdomain
local-zone: "twindors-casino.click." always_nxdomain
local-zone: "vegaz-casino.click." always_nxdomain
