server:
# Source: cbuijs NRD 1 Day
# URL: https://github.com/cbuijs/nrd
# Updated: 31/07/2026 20:54:00,50
# Total Domains: 66

local-zone: "2025-serial-smotrim.ru." always_nxdomain
local-zone: "aefh.eu.cc." always_nxdomain
local-zone: "agendia-app.com." always_nxdomain
local-zone: "ai-tool-compass.com." always_nxdomain
local-zone: "alphard-life.com." always_nxdomain
local-zone: "aperture-archi.fr." always_nxdomain
local-zone: "arta-co.com." always_nxdomain
local-zone: "book-concierge.com." always_nxdomain
local-zone: "cash-file.net." always_nxdomain
local-zone: "charcoal-ai.com." always_nxdomain
local-zone: "chicago--news.com." always_nxdomain
local-zone: "coody-us.com." always_nxdomain
local-zone: "counsel-mediate.com." always_nxdomain
local-zone: "dette-france.fr." always_nxdomain
local-zone: "dewalt-canada.com." always_nxdomain
local-zone: "dug-agency.com." always_nxdomain
local-zone: "elegancebeauty-group.com." always_nxdomain
local-zone: "erhardt-cc.com." always_nxdomain
local-zone: "eyecatch-bd.com." always_nxdomain
local-zone: "ezwin168-auto.com." always_nxdomain
local-zone: "fairgocasino-offcial-au.com." always_nxdomain
local-zone: "feisu-youku-alive.com." always_nxdomain
local-zone: "fin-frontier.com." always_nxdomain
local-zone: "flancy.spb.ru." always_nxdomain
local-zone: "ham-blog.com." always_nxdomain
local-zone: "healthcare-marketing-navi.com." always_nxdomain
local-zone: "hq-moving.com." always_nxdomain
local-zone: "ifeng-nb.com." always_nxdomain
local-zone: "i-loop.in." always_nxdomain
local-zone: "j-puls.com." always_nxdomain
local-zone: "leah-berg.com." always_nxdomain
local-zone: "leto-perm.ru." always_nxdomain
local-zone: "mas-tv.com." always_nxdomain
local-zone: "mrtaxes-ca.com." always_nxdomain
local-zone: "mued-lighting.com." always_nxdomain
local-zone: "nakelovinch-ai.com." always_nxdomain
local-zone: "nature-me.com." always_nxdomain
local-zone: "ok-insight.com." always_nxdomain
local-zone: "otc-crypto.com." always_nxdomain
local-zone: "othala-family-bc.com." always_nxdomain
local-zone: "pbbhaus-app.com." always_nxdomain
local-zone: "petronic-wh.com." always_nxdomain
local-zone: "planitarxis-insider.com." always_nxdomain
local-zone: "plateau-ai.com." always_nxdomain
local-zone: "proactivecleaning-or.com." always_nxdomain
local-zone: "psicomania-store.com." always_nxdomain
local-zone: "pulse-axis.com." always_nxdomain
local-zone: "quail-cs.com." always_nxdomain
local-zone: "redirectme-secure-sign-in.com." always_nxdomain
local-zone: "reiseberichte-europa.de." always_nxdomain
local-zone: "sogestionproprete-toulouse.fr." always_nxdomain
local-zone: "strange-future.com." always_nxdomain
local-zone: "techni-corp.com." always_nxdomain
local-zone: "the-secret-door.com." always_nxdomain
local-zone: "theswitch-academy.com." always_nxdomain
local-zone: "tickets-costco.com." always_nxdomain
local-zone: "veronika-law.com." always_nxdomain
local-zone: "w1-brackens-pg.com." always_nxdomain
local-zone: "wanova-shop.com." always_nxdomain
local-zone: "wanqiulive-dongqiudi.com." always_nxdomain
local-zone: "wevu-store.com." always_nxdomain
local-zone: "winamax-bet.com." always_nxdomain
local-zone: "yago-store.com." always_nxdomain
local-zone: "yhufsdatsiujtoueawtewfyestryasg.eu.cc." always_nxdomain
local-zone: "zenvio-digital.com." always_nxdomain
local-zone: "zonaluxbit-ai.com." always_nxdomain
